apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: contact-persistence-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: contact-persistence
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
