name: CI Pipeline - Contact Persistence Microservice

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./ContactPersistence.sln
      
    - name: Build
      run: dotnet build ./ContactPersistence.sln --no-restore
      
    - name: Test
      run: dotnet test ./ContactPersistence.sln --no-build --verbosity normal
